/-
Copyright (c) 2026 Christian Reitwiessner. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Christian Reitwiessner
-/

module

public import Cslib.Computability.Machines.MultiTapeTuring.Basic
public import Cslib.Computability.Machines.MultiTapeTuring.TapeView
public import Cslib.Computability.Machines.MultiTapeTuring.StructuralMachines
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.Navigation
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.Copy
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.Eq
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.Put
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.ListIteration
public import Cslib.Computability.Machines.MultiTapeTuring.Routines.Typed
import Mathlib.Order.Interval.Finset.Defs

namespace Turing

namespace UniversalTM

open Routines

variable [Inhabited Symbol] [Fintype Symbol] [StrEnc Symbol]

/-- The cell of a single Turing tape. -/
public structure TapeCell Symbol where
  /-- The symbol in the cell. -/
  c : Option Symbol
  /-- If the head is at this cell currently. -/
  containsHead : Bool

public instance : StrEnc (TapeCell Symbol) where
  toData cell := StrEnc.toData (cell.c, cell.containsHead)

public instance (α : Type) [StrEnc α] (k : ℕ) : StrEnc (Vector α k) where
  toData v := StrEnc.toData v.toList

/-
Outline of UTM:
while the current state is not None:
- for each tape, find the head position on the multi-tape
  and copy the current symbol to an aux tape.
- now the aux tape contains the symbols in the correct order.
- copy the current state to the aux tape.
- the contents of the aux tape is exactly the input to the
  transition function
- "evaluate the transition function" by iterating through its
  table and storing the result on another tape
- execute the actions for each of the tapes:
  - find the head. update the symbol, update the head marking
    according to the move action
    (potentially extend the tape to the left or right)
- update the current state
-/

/- sub-routines we need:
- move to the first element of a list that satisfies a condition:
  tm₁ tm₂ tm₃: For each item in the list: if tm₁ outputs true on an aux tape, run tm₂.
  if it never outputs true, run tm₃
- evaluate a function given by a list of input-output pairs
- update an element in a list, whose encoding size must be the same
- extend a list to the right
-/


/-- Parameters for encoding a tuple of tapes as a single tape with multiple tracks. -/
public structure EncodingParams (k : ℕ) where
  /-- The encoding start for each tape, relative to the tape head. -/
  start : Fin k → ℤ
  /-- The number of cells to encode. -/
  length : ℕ

/-- The encoding of a tuple of tapes as a list of tuples of `TapeCell`s.
Note that the encoding can only be decoded for some values of `params`. -/
public def encodeTapes {k : ℕ} (tapes : Fin k → BiTape Symbol) (params : EncodingParams k) :
    List (Fin k → TapeCell Symbol) :=
  List.ofFn (n := params.length) fun p i =>
    {
      c := (tapes i).get ((params.start i) + p)
      containsHead := (params.start i) + p == 0
    }

/-- The parameters are such that position `cellPos` of tape `tapeIdx` is part of the encoding. -/
public def EncodingParams.encodesCell {k : ℕ} (params : EncodingParams k)
    (tapeIdx : Fin k) (cellPos : ℤ) : Prop :=
  (params.start tapeIdx) ≤ cellPos ∧ cellPos - (params.start tapeIdx) < (params.length : ℤ)

/-- The parameters are suitable to encode all relevant information of the tape. -/
public def encodesTape {k : ℕ} (params : EncodingParams k) (tapes : Fin k → BiTape Symbol) : Prop :=
  ∀ idx,
    -- the head is encoded
    params.encodesCell idx 0 ∧
    -- all non-none cells are encoded
    ∀ i, (tapes idx).get i ≠ none → params.encodesCell idx i


/-- The encoding of tapes generated by `encodeTapes` plus a proof that we properly encoded the tape. -/
public structure EncodedTapes (k : ℕ) where
  /-- The tapes -/
  tapes : Fin k → BiTape Symbol
  /-- The encoding params -/
  params : EncodingParams k
  /-- The encoding is valid -/
  h_vallid : encodesTape params tapes

instance (k : ℕ) : StrEnc (EncodedTapes k (Symbol := Symbol)) where
  toData enc := StrEnc.toData (encodeTapes enc.tapes enc.params)

omit [Inhabited Symbol] [Fintype Symbol] [StrEnc Symbol] in
/-- If a cell in the encoding is marked as containing the head, then its symbol is the
current head symbol of the corresponding tape. -/
@[simp, grind =]
lemma encodeTapes_getElem_of_containsHead {k : ℕ}
    {t : Fin k → BiTape Symbol} {params : EncodingParams k}
    {idx : ℕ} (h_idx_lt : idx < (encodeTapes t params).length) {i : Fin k}
    (h : (((encodeTapes t params)[idx]'h_idx_lt) i).containsHead) :
    ((encodeTapes t params)[idx]'h_idx_lt) i = {c := (t i).head, containsHead := true} := by
  simp_all [encodeTapes, BiTape.get]

/-- The minimal head positions over all tapes at step `t` starting from initial zero positions. -/
public def minHeadPos
  {k : ℕ} (tm : MultiTapeTM k Symbol) (initialTapes : Fin k → BiTape Symbol) (t : ℕ) : ℤ :=
  (List.ofFn (tm.headPosition initialTapes t)).min?.getD 0

/-- The maximal head positions over all tapes at step `t` starting from initial zero positions. -/
public def maxHeadPos
  {k : ℕ} (tm : MultiTapeTM k Symbol) (initialTapes : Fin k → BiTape Symbol) (t : ℕ) : ℤ :=
  (List.ofFn (tm.headPosition initialTapes t)).max?.getD 0

-- TODO use this sequence of encoding parameters.

/-- The execution sequence of tape encoding parameters. -/
public def encodingParamSequence {k : ℕ} (tm : MultiTapeTM k Symbol)
    (initialTapes : Fin k → BiTape Symbol) (t : ℕ) : EncodingParams k :=
  let headPositions := tm.headPosition initialTapes
  -- The min head position over all tapes at a specific step
  let minHeadPosAtStep := fun t' => (List.ofFn (headPositions t')).min?.getD 0
  let maxHeadPosAtStep := fun t' => (List.ofFn (headPositions t')).max?.getD 0
  -- The min head position over all tapes and all steps until step t
  -- TODO check for off-by-one errors here
  let minHeadPosUntil := (List.ofFn (n := t + 1) (fun t' => minHeadPosAtStep t')).min?.getD 0
  let maxHeadPosUntil := (List.ofFn (n := t + 1) (fun t' => maxHeadPosAtStep t')).max?.getD 0
  let length := 1 + (maxHeadPosUntil - minHeadPosUntil).toNat
  let start := fun i => (headPositions t i) - minHeadPosUntil
  ⟨ start, length ⟩

/-- The next tape encoding parameter set given the previous one. -/
public def updateEncodingParams {k : ℕ} (tm : MultiTapeTM k Symbol)
  (params : EncodingParams k)
  (cfg : tm.Cfg) : EncodingParams k := sorry
  -- match cfg with
  -- | ⟨none, _⟩ => (fun _ => 0)
  -- | ⟨some q, tapes⟩ =>
  --   match tm.tr q (fun i => (tapes i).head) with
  --   | ⟨stmts, _⟩ => fun i => shifts i + (match (stmts i).movement with
  --     | none => 0
  --     | .some .right => 1
  --     | .some .left => -1)

/-- Copies the symbol under the head of tape `tapeIdx` from the multi-track tape `tape` to
tape `out` using the auxiliary tape `aux`. -/
def getHeadSymbol (k : ℕ) (tapeIdx : ℕ) (tapes out aux : Fin k) : MultiTapeTM k Char :=
  find_list tapes aux
    -- Find the cell where the tapeIdx-th tape has the head
    (atPath [tapeIdx, 1] tapes (copyEnc tapes aux))
    -- copy the symbol to out and move back to the start of the list.
    (atPath [tapeIdx, 0] tapes (copy_to_list tapes out) ;ₜ outOfList tapes)
    -- otherwise do nothing (because we know there is a head marker)
    (noop)


omit [Fintype Symbol] [Inhabited Symbol] in
lemma geatHeadSymbol.semantics {k k' : ℕ} (tapeIdx : Fin k') (tapes out aux : Fin k)
    (h_distinct : [tapes, aux, out].get.Injective)
    {views : Fin k → TapeView}
    {encodedTapes : EncodedTapes k' (Symbol := Symbol)}
    (h_tapes : views tapes = .ofEnc encodedTapes)
    (h_aux : views aux = TapeView.empty)
    (outl : List (Option Symbol))
    (h_outl : views out = .ofEnc outl) :
    (getHeadSymbol k tapeIdx tapes out aux).eval_struct views = .some (Function.update
      views out (TapeView.ofEnc ((encodedTapes.tapes tapeIdx).head :: outl))) := by
  have h_tapes_aux : tapes ≠ aux :=
    Function.Injective.ne h_distinct (show (0 : Fin 3) ≠ 1 by decide)
  have h_tapes_out : tapes ≠ out :=
    Function.Injective.ne h_distinct (show (0 : Fin 3) ≠ 2 by decide)
  have h_copyHeadPos :
      computes_function_read_update'
      (atPath [tapeIdx, 1] tapes (copyEnc tapes aux))
      (fun (tcs : Fin k' → TapeCell Symbol) _ => (tcs tapeIdx).containsHead)
      tapes aux :=
      atPath_computes_function h_tapes_aux
        (h_tm := copyEnc_computes_fun h_tapes_aux)
        (h_path := by simp [StrEnc.toData])
  have h_copySymbol :
      computes_function_read_push'
      (atPath [tapeIdx, 0] tapes (copy_to_list tapes out))
      (fun (tcs : Fin k' → TapeCell Symbol) => (tcs tapeIdx).c)
      tapes out := by
    apply atPath_computes_function h_tapes_out
      (h_tm := copy_to_list.computes_fun' h_tapes_out)
      (h_path := by simp [StrEnc.toData])
  -- Derive the head index and the `findIdx?` equation from the validity of `encodedTapes`.
  set idx : ℕ := (-encodedTapes.params.start tapeIdx).toNat with hidx_def
  obtain ⟨hhead, _⟩ := encodedTapes.h_vallid tapeIdx
  have h_le : encodedTapes.params.start tapeIdx ≤ 0 := hhead.1
  have h_lt : (0 : ℤ) - encodedTapes.params.start tapeIdx < encodedTapes.params.length := hhead.2
  have hnn : 0 ≤ -encodedTapes.params.start tapeIdx := by omega
  have h_idx_eq : (idx : ℤ) = -encodedTapes.params.start tapeIdx := by grind
  have h_idx_lt : idx < (encodeTapes encodedTapes.tapes encodedTapes.params).length := by
    have hlt : (idx : ℤ) < encodedTapes.params.length := by rw [h_idx_eq]; omega
    have : idx < encodedTapes.params.length := by exact_mod_cast hlt
    simpa [encodeTapes] using this
  have h_pred :
      (((encodeTapes encodedTapes.tapes encodedTapes.params)[idx]'h_idx_lt) tapeIdx).containsHead =
        true := by
    have h0 : encodedTapes.params.start tapeIdx + (idx : ℤ) = 0 := by rw [h_idx_eq]; omega
    simp [encodeTapes, h0]
  have h_contains_head :
      (encodeTapes encodedTapes.tapes encodedTapes.params).findIdx?
        (fun c => (c tapeIdx).containsHead) = some idx := by
    rw [List.findIdx?_eq_some_iff_getElem]
    refine ⟨h_idx_lt, h_pred, ?_⟩
    intro j hji
    have hjlen : j < (encodeTapes encodedTapes.tapes encodedTapes.params).length := by omega
    have hjlen' : j < encodedTapes.params.length := by simpa [encodeTapes] using hjlen
    simp only [encodeTapes, List.getElem_ofFn]
    intro hbad
    have heq0 : encodedTapes.params.start tapeIdx + (j : ℤ) = 0 := by simpa using hbad
    have hj_eq : (j : ℤ) = -encodedTapes.params.start tapeIdx := by omega
    have : (j : ℤ) = idx := by rw [hj_eq, ← h_idx_eq]
    have : j = idx := by exact_mod_cast this
    omega
  unfold getHeadSymbol
  rw [find_list.computes_fun h_tapes_aux h_copyHeadPos views
      (encodeTapes encodedTapes.tapes encodedTapes.params)
        (by simp [h_tapes, StrEnc.toData]) h_aux]
  simp only [h_contains_head, TapeView.appendPath', seq_eval_struct]
  rw [h_copySymbol (encodeTapes encodedTapes.tapes encodedTapes.params)[idx]
        outl _
        (by simp [h_tapes, StrEnc.toData, h_idx_lt])
        (by simp [Function.update, h_outl, h_tapes_out.symm])]
  simp only [Part.bind_some, outOfList_eval_struct, Part.coe_some, Part.some_inj]
  rw [encodeTapes_getElem_of_containsHead h_idx_lt h_pred]
  simp
  grind

/-- Copies symbols under the heads of all tapes for `tapeCount` tapes from the multi-track
tape `tapes` to tape `out` using the auxiliary tape `aux`. -/
def getHeadSymbols (k : ℕ) (tapeCount : ℕ) (tapes out aux : Fin k) : MultiTapeTM k Char :=
  match tapeCount with
  | 0 => noop
  | tapeCount + 1 =>
    getHeadSymbol k tapeCount tapes out aux ;ₜ getHeadSymbols k tapeCount tapes out aux

/-- Execute a single step of the simulated machine. -/
public def utm_step : MultiTapeTM 10 Char := sorry

/-- Main theorem -/
public theorem utm_step_semantics
  {k : ℕ} (tm : MultiTapeTM k Symbol)
  [StrEnc tm.State] -- it is a fintype, so easy to satsify
  (cfg : tm.Cfg)
  (views : Fin 10 → TapeView)
  (params : EncodingParams k)
  (h_tapes : views 1 = .ofEnc (encodeTapes cfg.tapes params))
  (h_state : views 2 = .ofEnc cfg.state) :
  utm_step.eval_struct views = .some (match tm.step cfg with
    | none => views
    | some cfg' => Function.update (Function.update views
      1 (.ofEnc (encodeTapes cfg'.tapes (updateEncodingParams tm params cfg))))
      2 (.ofEnc cfg'.state)) := by sorry

end UniversalTM

end Turing
